### ISSUE TITLE
One question about the result

### ISSUE THREAD

**Issue by JasonSheng-atp** [yael-vinker/unpaired_hdr_tmo#1]
Hi, I encountered one problem when I use the default belgium.hdr for inference.
![test](https://user-images.githubusercontent.com/78075051/160094856-374da5e7-e8c8-471e-ac36-b25c1f3a429f.png)
There is a darker part on the upper edge of the door. I wonder if it is normal ?

**Comment by yael-vinker** [comment]
Hi and thanks for your interest in our work.
Sometimes such artifacts are observed and they are probably caused by the GAN loss.
Training without the third level of L_natural might be a way to overcome this, based on our experiences.
A simpler option would be to increase the lambda value.

Let me know if I can help with anything else.

**Comment by JasonSheng-atp** [comment]
Thank you for your reply. I will try to increase the lambda value.
